# Generated by Django 4.1.2 on 2022-10-19 15:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "documentID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                ("entityID", models.URLField(primary_key=True, serialize=False)),
                ("abstract", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "instanceID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start", models.IntegerField()),
                ("stop", models.IntegerField()),
                (
                    "documentID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entity_app.document",
                    ),
                ),
                (
                    "entityID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entity_app.entity",
                    ),
                ),
            ],
        ),
    ]
