# Generated by Django 4.1.2 on 2022-10-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.FileField(upload_to=''),
        ),
    ]
