# Generated by Django 4.1.2 on 2022-10-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0003_file_alter_document_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='text',
            new_name='txtfile',
        ),
    ]
