# Generated by Django 4.1.2 on 2022-10-28 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0005_alter_file_txtfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
