# Generated by Django 4.1.2 on 2022-11-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0006_document_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='sensitivity',
            field=models.IntegerField(default=0),
        ),
    ]
