# Generated by Django 4.1.2 on 2023-01-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0007_entity_sensitivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tokens',
            field=models.TextField(null=True),
        ),
    ]
