# Generated by Django 4.1.2 on 2023-01-28 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0008_document_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicWord',
            fields=[
                ('topicWordID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity_app.entity')),
            ],
        ),
        migrations.CreateModel(
            name='LDATopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('topicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity_app.topicword')),
            ],
        ),
    ]
