# Generated by Django 4.1.2 on 2023-01-28 17:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0009_topicword_ldatopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDA',
            fields=[
                ('ldaID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='topicword',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='LDATopic',
        ),
        migrations.AddField(
            model_name='topic',
            name='topicWordID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity_app.topicword'),
        ),
        migrations.AddField(
            model_name='lda',
            name='topicID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity_app.topic'),
        ),
    ]
