# Generated by Django 4.1.2 on 2023-01-28 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0010_lda_topic_topicword_weight_delete_ldatopic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topicWordID',
        ),
        migrations.AddField(
            model_name='topicword',
            name='topicNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LDA',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
