# Generated by Django 4.1.2 on 2023-01-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0012_remove_topicword_topicnumber_remove_topicword_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicword',
            name='topicNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicword',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
