# Generated by Django 4.1.2 on 2023-01-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0013_topicword_topicnumber_topicword_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
