# Generated by Django 4.1.2 on 2023-01-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0015_topicdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filetitle',
            field=models.TextField(null=True),
        ),
    ]
