# Generated by Django 4.1.2 on 2023-02-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_app', '0016_document_filetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='slug',
            field=models.TextField(null=True),
        ),
    ]
